### PR TITLE
Arduino library name change to avdweb_Switch

### PR DESCRIPTION
**Pull request by Martin-Laclaustra**
Change the name which is used in the Arduino libraries. This way the arduino library name is consistent with the include directive (avdweb_Switch)

### CODE REVIEW

**Comment by Martin-Laclaustra** [comment]
As the class is still named "Switch" this might not be appropriate.
What are your thoughts about consistency across "names"? Why did you decide to change the filenames and library folder name?
Will "Switch" potentially clash with some keyword/class of the Arduino or ESP cores?

**Comment by avandalen** [comment]
The library was called Switch some years ago and just recent I name all my libraries avdweb_blabla.

**Comment by Martin-Laclaustra** [comment]
@avandalen 
Dear Albert,
I have been thinking that changing the name of the library and the files will break former projects that rely on this library, given that it has been published in the Arduino libraries list.
I request your permission to revert back to the original name before preparing a release. I believe that you receive equal credit appearing as the author, and you lose little removing your initials from the:
a) cpp and h file names
b) library name (in the properties file)
c) github repository
Please let me know if you agree and your thoughts in this regard.
Best regards!

**Comment by avandalen** [comment]
Hello Martin

>>>I have been thinking that changing the name of the library and the files will break former projects that rely on this library, given that it has been published in the Arduino libraries list.
yes this is true

Further you can do what you want.

An idea is to take the switch class as parent and make derived classes for other processors

best regards

Albert

**Pull request merged**
